### ISSUE TITLE
Computation doesn't work in Firefox. Module workers not support. Need a workaround.

### ISSUE THREAD

**Issue by glamperd** [zkparty/setup-mpc-ui#5]
small-pot is built to wasm using wasm-pack-rayon. The build ends up as a module to be imported, which means the web worker is invoked as a worker module. That works fine in almost all browsers in version from recent years, but not in Firefox. We'll need a workaround as we need to cater for FF users. 
Possible approaches:
- Manually refactor worker.js so it can be loaded as a script. 
- Make a single-threaded version just for Firefox, and build it using wasm-pack's no-modules target.
- Manually manage the web worker creation and build the wasm code with an entry point to suit.

**Comment by NicoSerranoP** [comment]
I think the easiest/most generic way to solve this issue is the second option "Make a single-threaded version for Firefox and non support browsers and a threaded version for all compatible browsers". 

To identify the feature compatibility we can use the [wasm-feature-detect](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#feature-detection).

**Comment by NicoSerranoP** [comment]
After a couple of days (and nights) reviewing this problem I found the solution which I want to document here for future reference.

### Problem
Module Web Workers are not supported on Firefox yet. For more information check [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687)

### Solution
Use a [polyfill](https://gist.github.com/developit/220246bc99044af74a6680ce13284f59) that would get activated only when the Worker object in the browser does not accept type 'module' in the options object at initialization. This way, a module worker in Firefox can be executed and the same codebase can be used in both browsers.

But this does not solves the issue entirely because inside the web workers we have Javascript/Typescript code written in ES6 module way, so Firefox browsers are not going to be able to execute them. That is why we need to compile the rust code from [small-pot](https://github.com/zkparty/small-powers-of-tau) using a specific file in the Cargo.toml file (```no-bundles```). This flag announces the compiler that no bundle (like Webpack or Parcel) are being used in the serving application (the React app in our case). 

Even though no-bundled code can run in Firefox and Chrome, we decided to split the compilation and the web workers calling them in two: one for Firefox with no-bundled web workers and one for Chrome with normal module web workers). For instructions on how to do that, please check the readme.md in the small-pot project.

### Workflow
1. Compile rust code for Firefox (no-bundled flag activated)
2. Compile rust code for Brave (no special flag required)
3. Use the same codebase (polyfill will take care of Firefox issue)
4. Execute the web workers depending on your browser (pkg-chrome or pkg-firefox)


Keep in mind that the Firefox computation can go a bit slower than the Chrome computation because the code used in Firefox is bigger in size than the one used on Chrome. Both processes are using multi-threading enabled by [wasm-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon).
